version: "3"

services:
  latest:
    image: ${IMAGE}
    healthcheck:
      test: curl --fail http://localhost:3000 || exit 1
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 3s
  
  health:
    image: busybox
    command: id
    depends_on:
      latest:
        condition: service_healthy